version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hotel_postgres
    environment:
      POSTGRES_USER: hoteluser
      POSTGRES_PASSWORD: hotelpass
      POSTGRES_DB: hoteldb
    ports:
      - "5432:5432"
    volumes:
      - hotel_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: hotel_redis
    ports:
      - "6379:6379"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: hotel_zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: hotel_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  eureka-server:
    build: ./config-server
    container_name: hotel_eureka
    ports:
      - "8761:8761"
    depends_on:
      - postgres

volumes:
  hotel_pg_data:
